version: '3'

services:
  # WARNING: The name of this service must be identical to the MQTT_BROKER_SERVICE_NAME defined in the .env file
  mqtt-service:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt-service/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  image-dispatcher-service:
    build: ./image-dispatcher-service
    volumes:
      - ./image-dispatcher-service:/app
    depends_on:
      - ${MQTT_BROKER_SERVICE_NAME}
    ports:
      - "${WEB_SOCKET_PORT}:${WEB_SOCKET_PORT}"
    environment:
      - MQTT_BROKER_SERVICE_NAME=${MQTT_BROKER_SERVICE_NAME} 
      - WEB_SOCKET_PORT=${WEB_SOCKET_PORT} 
      - MQTT_IMAGE_TOPIC=${MQTT_IMAGE_TOPIC}
  
  image-generator-service:
    build: ./image-generator-service
    volumes:
      - ./image-generator-service:/app
    depends_on:
      - ${MQTT_BROKER_SERVICE_NAME}
    environment:
      - MQTT_BROKER_SERVICE_NAME=${MQTT_BROKER_SERVICE_NAME} 
      - IMAGE_GENERATION_INTERVAL_IN_SECONDS=${IMAGE_GENERATION_INTERVAL_IN_SECONDS} 
      - MQTT_IMAGE_TOPIC=${MQTT_IMAGE_TOPIC}

  client-app:
    build: ./client-app
    volumes:
      - ./client-app:/app
      - /app/node_modules
    ports:
      - "${CLIENT_APP_PORT}:${CLIENT_APP_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_WEB_SOCKET_HOST_NAME=${WEB_SOCKET_HOST_NAME}
      - REACT_APP_WEB_SOCKET_PORT=${WEB_SOCKET_PORT}
